apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
    log
    errors
    health
    ready
    kubernetes cluster.local in-addr.arpa ip6.arpa {
      pods insecure
      fallthrough in-addr.arpa ip6.arpa
    }
    hosts /etc/coredns/NodeHosts {
      ttl 60
      reload 15s
      fallthrough
    }
    rewrite name substring .com.it-lab.cc .com
    rewrite name substring api.cloudflare.com .com
    prometheus :9153
    forward . 172.30.100.1
    cache 30
    loop
    reload
    loadbalance
    import /etc/coredns/custom/*.override
    }
