apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: alertmanager
  ports:
    - name: web
      port: 9093
      targetPort: web
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alertmanager
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: default-cors@kubernetescrd,default-redirectscheme@kubernetescrd
spec:
  rules:
    - host: alertmanager.k3s.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: alertmanager
                port:
                  number: 9093
