apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-key
  namespace: external-dns
type: Opaque
stringData:
  api-key: '<api-key>'
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-key
  namespace: kube-system
type: Opaque
stringData:
  api-key: '<api-key>'
