apiVersion: v1
data:
  config.yml: |
    ---
    # Homepage configuration
    # See https://fontawesome.com/v5/search for icons options

    # Optional: Use external configuration file.
    # Using this will ignore remaining config in this file
    # externalConfig: https://example.com/server-luci/config.yaml

    title: 'IT-Lab'
    subtitle: 'Hub'
    # documentTitle: "Welcome" # Customize the browser tab text
    logo: 'https://www.openkonsequenz.de/medien/cache/member_logo/l_15_coundandcare-1.jpg'
    # Alternatively a fa icon can be provided:
    # icon: "fas fa-skull-crossbones"

    header: true # Set to false to hide the header
    # Optional: Different hotkey for search, defaults to "/"
    # hotkey:
    #   search: "Shift"
    footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

    columns: '3' # "auto" or number (must be a factor of 12: 1, 2, 3, 4, 6, 12)
    connectivityCheck:
      true # whether you want to display a message when the apps are not accessible anymore (VPN disconnected for example).
      # You should set it to true when using an authentication proxy, it also reloads the page when a redirection is detected when checking connectivity.

    # Optional: Proxy / hosting option
    proxy:
      useCredentials: false # send cookies & authorization headers when fetching service specific data. Set to `true` if you use an authentication proxy. Can be overrided on service level.

    # Set the default layout and color scheme
    defaults:
      layout: columns # Either 'columns', or 'list'
      colorTheme: auto # One of 'auto', 'light', or 'dark'

    # Optional theming
    theme: default # 'default' or one of the themes available in 'src/assets/themes'.

    # Optional custom stylesheet
    # Will load custom CSS files. Especially useful for custom icon sets.
    # stylesheet:
    #   - "assets/custom.css"

    # Here is the exhaustive list of customization parameters
    # However all value are optional and will fallback to default if not set.
    # if you want to change only some of the colors, feel free to remove all unused key.
    colors:
      light:
        highlight-primary: '#3367d6'
        highlight-secondary: '#4285f4'
        highlight-hover: '#5a95f5'
        background: '#f5f5f5'
        card-background: '#ffffff'
        text: '#363636'
        text-header: '#424242'
        text-title: '#303030'
        text-subtitle: '#424242'
        card-shadow: rgba(0, 0, 0, 0.1)
        link: '#3273dc'
        link-hover: '#363636'
        # background-image: 'assets/your/light/bg.png'
      dark:
        highlight-primary: '#3367d6'
        highlight-secondary: '#4285f4'
        highlight-hover: '#5a95f5'
        background: '#131313'
        card-background: '#2b2b2b'
        text: '#eaeaea'
        text-header: '#ffffff'
        text-title: '#fafafa'
        text-subtitle: '#f5f5f5'
        card-shadow: rgba(0, 0, 0, 0.4)
        link: '#3273dc'
        link-hover: '#ffdd57'
        # background-image: 'assets/your/dark/bg.png'

    # Optional message
    # message:
    # url: "https://<my-api-endpoint>" # Can fetch information from an endpoint to override value below.
    # mapping: # allows to map fields from the remote format to the one expected by Homer
    #   title: 'id' # use value from field 'id' as title
    #   content: 'value' # value from field 'value' as content
    # refreshInterval: 10000 # Optional: time interval to refresh message
    #
    # Real example using chucknorris.io for showing Chuck Norris facts as messages:
    # url: https://api.chucknorris.io/jokes/random
    # mapping:
    #   title: 'id'
    #   content: 'value'
    # refreshInterval: 10000
    # style: 'is-warning'
    # title: 'Optional message!'
    # icon: 'fa fa-exclamation-triangle'
    # content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.'

    # Optional navbar
    # links: [] # Allows for navbar (dark mode, layout, and search) without any links
    links:
      - name: 'Heimdall (old)'
        icon: 'fas fa-home'
        url: 'https://hub.it-lab.cc'
        target: '_blank' # optional html tag target attribute
      # - name: 'link 2'
      #   icon: 'fas fa-book'
      #   url: 'https://github.com/bastienwirtz/homer'
      # this will link to a second homer page that will load config from page2.yml and keep default config values as in config.yml file
      # see url field and assets/page.yml used in this example:
      # - name: 'Second Page'
      #   icon: 'fas fa-file-alt'
      #   url: '#page2'

    # Services
    # First level array represents a group.
    # Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
    services:
      - name: 'Lab Production'
        icon: 'fas fa-code-branch'
        # A path to an image can also be provided. Note that icon take precedence if both icon and logo are set.
        # logo: "path/to/logo"
        items:
          - name: 'Wiki'
            icon: 'fab fa-wikipedia-w'
            subtitle: 'IT-Lab Wiki'
            tag: 'app'
            url: 'https://wiki.it-lab.cc/de/home'
            type: 'Ping'
          - name: 'Wiki (K3s-Test)'
            icon: 'fab fa-wikipedia-w'
            subtitle: 'IT-Lab Wiki'
            tag: 'app'
            url: 'https://wiki.k3s.it-lab.cc/de/home'
            type: 'Ping'
          - name: 'Nextcloud'
            icon: 'fab fa-cloudversify'
            subtitle: 'Nextcloud'
            tag: 'app'
            url: 'https://nc.it-lab.cc/'
            type: 'Ping'
          - name: 'Vaultwarden'
            icon: 'fas fa-key'
            subtitle: 'Vaultwarden'
            tag: 'app'
            url: 'https://vault.it-lab.cc/'
            type: 'Ping'
          - name: 'UniFi'
            icon: 'fas fa-wifi'
            subtitle: 'UniFi'
            tag: 'app'
            url: 'https://unifi.it-lab.cc/'
            type: 'Ping'
          - name: 'Rundgang'
            icon: 'fas fa-map-signs'
            subtitle: 'Rundgang'
            tag: 'app'
            url: 'https://rundgang.it-lab.cc/'
      - name: 'Monitoring'
        icon: 'fas fa-heartbeat'
        items:
          - name: 'Grafana'
            # logo: 'https://upload.wikimedia.org/wikipedia/commons/3/39/Kubernetes_logo_without_workmark.svg'
            # Alternatively a fa icon can be provided:
            icon: 'fas fa-gauge-high'
            subtitle: 'Grafana'
            url: 'https://grafana.it-lab.cc/'
            type: 'Ping'
          - name: 'Prometheus'
            icon: 'fas fa-network-wired'
            subtitle: 'Prometheus'
            type: Prometheus
            url: 'https://prometheus.it-lab.cc/'
          - name: 'Alertmanager'
            icon: 'fas fa-toolbox'
            url: 'https://alertmanager.it-lab.cc/#/alerts'
            type: 'Ping'
            method: 'GET'
          - name: 'Uptime Kuma'
            icon: 'fas fa-tv'
            url: 'https://monitor.it-lab.cc'
            type: 'UptimeKuma'
            slug: 'all'
      - name: 'Monitoring (K3s-Test)'
        icon: 'fas fa-heartbeat'
        items:
          - name: 'Prometheus'
            icon: 'fas fa-network-wired'
            subtitle: 'Prometheus'
            type: Prometheus
            url: 'https://prometheus.k3s.it-lab.cc/'
          - name: 'Alertmanager'
            icon: 'fas fa-toolbox'
            url: 'https://alertmanager.k3s.it-lab.cc/#/alerts'
            type: 'Ping'
            method: 'GET'
          - name: 'Uptime Kuma'
            icon: 'fas fa-tv'
            url: 'https://monitor.k3s.it-lab.cc'
            type: 'UptimeKuma'
            slug: 'all'
      - name: 'Octoprint'
        icon: 'fab fa-octopus-deploy'
        items:
          - name: 'Ender 3 S1 Pro'
            icon: 'fas fa-print'
            url: 'https://s1.it-lab.cc/'
            type: 'Ping'
          - name: 'Ender 3 Pro Toni'
            icon: 'fas fa-print'
            url: 'https://pro-toni.it-lab.cc/'
            type: 'Ping'
          - name: 'Ender 3 Pro Lucas'
            icon: 'fas fa-print'
            url: 'https://pro-lucas.it-lab.cc/'
            type: 'Ping'
          - name: '3D-Drucker-Landschaft Portnainer'
            icon: 'fas fa-toolbox'
            url: 'https://portainer.3d-drucker.it-lab.cc/'
            type: 'Ping'
      - name: 'Wetterstation'
        icon: 'fas fa-sun'
        items:
          - name: 'LuftDB'
            icon: 'fas fa-database'
            url: 'https://luftdb.it-lab.cc/'
            type: 'Ping'
          - name: 'Luftdaten (Wettersation)'
            icon: 'fas fa-thermometer-half'
            url: 'https://luft.it-lab.cc/'
            type: 'Ping'
          - name: 'Portainer Wetterstation'
            icon: 'fas fa-toolbox'
            url: 'https://portainer.luft.it-lab.cc/'
            type: 'Ping'
      - name: 'Kubernetes (K3s-Test)'
        icon: 'fas fa-heartbeat'
        items:
          - name: 'Kubernetes Dashboard'
            # logo: 'https://upload.wikimedia.org/wikipedia/commons/3/39/Kubernetes_logo_without_workmark.svg'
            # Alternatively a fa icon can be provided:
            icon: 'fas fa-gauge-high'
            subtitle: 'Kubernetes Dashboard'
            url: 'https://172.30.62.166:8443/'
            type: 'Ping'
          - name: 'Traefik Dashboard'
            icon: 'fas fa-network-wired'
            subtitle: 'Traefik Dashboard'
            url: 'http://172.30.62.166:9000/dashboard/'
            type: 'Ping'
          - name: 'Chest System'
            icon: 'fas fa-toolbox'
            url: 'https://chest.k3s.it-lab.cc/'
            type: 'Ping'
          - name: 'WhoAmI'
            icon: 'fas fa-toolbox'
            url: 'https://whoami.k3s.it-lab.cc/'
            type: 'Ping'
kind: ConfigMap
metadata:
  name: homer-config
  namespace: homer-ns
