apiVersion: v1
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app.kubernetes.io/instance: homer
        app.kubernetes.io/name: homer
      name: homer
      namespace: homer-ns
    spec:
      replicas: 1
      revisionHistoryLimit: 3
      selector:
        matchLabels:
          app.kubernetes.io/instance: homer
          app.kubernetes.io/name: homer
      strategy:
        rollingUpdate:
          maxSurge: 25%
          maxUnavailable: 25%
        type: RollingUpdate
      template:
        metadata:
          creationTimestamp: null
          labels:
            app.kubernetes.io/instance: homer
            app.kubernetes.io/name: homer
        spec:
          automountServiceAccountToken: true
          containers:
            - image: ghcr.io/bastienwirtz/homer:v23.05.1
              imagePullPolicy: IfNotPresent
              livenessProbe:
                failureThreshold: 3
                periodSeconds: 10
                successThreshold: 1
                tcpSocket:
                  port: 8080
                timeoutSeconds: 1
              name: homer
              ports:
                - containerPort: 8080
                  name: http
                  protocol: TCP
              readinessProbe:
                failureThreshold: 3
                periodSeconds: 10
                successThreshold: 1
                tcpSocket:
                  port: 8080
                timeoutSeconds: 1
              resources: {}
              startupProbe:
                failureThreshold: 30
                periodSeconds: 5
                successThreshold: 1
                tcpSocket:
                  port: 8080
                timeoutSeconds: 1
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - mountPath: /www/assets/config.yml
                  name: config
                  subPath: config.yml
          dnsPolicy: ClusterFirst
          enableServiceLinks: true
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          serviceAccount: default
          serviceAccountName: default
          terminationGracePeriodSeconds: 30
          volumes:
            - configMap:
                defaultMode: 420
                name: homer-config
              name: config
    status:
      availableReplicas: 1
      conditions:
        - lastTransitionTime: '2023-09-18T16:55:22Z'
          lastUpdateTime: '2023-09-18T16:55:22Z'
          message: Deployment has minimum availability.
          reason: MinimumReplicasAvailable
          status: 'True'
          type: Available
        - lastTransitionTime: '2023-09-18T16:55:15Z'
          lastUpdateTime: '2023-09-18T16:55:22Z'
          message: ReplicaSet "homer-5bd84949f5" has successfully progressed.
          reason: NewReplicaSetAvailable
          status: 'True'
          type: Progressing
      observedGeneration: 1
      readyReplicas: 1
      replicas: 1
      updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ''
