apiVersion: v1
kind: Service
metadata:
  name: prometheus-frontends
  namespace: monitoring
spec:
  ports:
    - name: web
      port: 9090
      targetPort: web
  selector:
    prometheus: prometheus-frontends
  sessionAffinity: ClientIP
