apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: example-app
  labels:
    name: example-app
    team: frontend
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: example-app
  namespaceSelector:
    any: true
  endpoints:
    - port: web
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
      scheme: http
      tlsConfig:
        insecureSkipVerify: true
# ---
# apiVersion: monitoring.coreos.com/v1
# kind: ServiceMonitor
# metadata:
#   name: whoami
#   labels:
#     team: frontend
# spec:
#   selector:
#     matchLabels:
#       io.custom.label: whoami
#   namespaceSelector:
#     any: true
#   endpoints:
#     - port: web
# ---
# # ServiceMonitor for CodeDNS
# apiVersion: monitoring.coreos.com/v1
# kind: ServiceMonitor
# metadata:
#   name: codedns
#   labels:
#     team: frontend
# spec:
#   selector:
#     matchLabels:
#       k8s-app: kube-dns
#   namespaceSelector:
#     any: true
#   endpoints:
#     - port: metrics
#       interval: 30s
#       path: /metrics
#       scheme: http
# ---

