---
apiVersion: v1
kind: ConfigMap
metadata:
  name: blocky-config
  namespace: blocky
data:
  config.yml: |-
    upstream:
      default:
        - unbound-svc.unbound.svc.cluster.local
        # - 1.1.1.1
    blocking:
      blackLists:
        ads:
          - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
          - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
        special:
          - https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews/hosts
      clientGroupsBlock:
        default:
          - ads
    port: 53
    httpPort: 4000
    caching:
      minTime: 5m
      maxTime: 30m
      prefetching: true
    customDNS:
      customTTL: 1h
      filterUnmappedTypes: true
      mapping:
        fwsense.box: 10.27.27.4
        cattle.box: 10.27.27.40
        dev.box: 10.27.27.121

---
apiVersion: v1
kind: Service
metadata:
  name: blocky-service
  namespace: blocky
spec:
  selector:
    app: blocky
  ports:
    - port: 4000
      targetPort: 4000
      name: blocky-admin
    - port: 53
      targetPort: 53
      protocol: TCP
      name: dns-tcp
    - port: 53
      targetPort: 53
      protocol: UDP
      name: dns-udp
  externalIPs:
    - 192.168.178.104
    - 192.168.178.66
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: blocky
  namespace: blocky
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: blocky
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 20
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 100Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blocky
  namespace: blocky
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blocky
  template:
    metadata:
      labels:
        app: blocky
    spec:
      containers:
        - name: blocky
          image: spx01/blocky
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: Asia/Kolkata
          resources:
            limits:
              cpu: 500m
              memory: 150Mi
            requests:
              cpu: 20m
              memory: 100Mi
          ports:
            - name: svc-53-udp
              containerPort: 53
              protocol: UDP
            - name: svc-53-tcp
              containerPort: 53
              protocol: TCP
            - name: svc-4000-tcp
              containerPort: 4000
              protocol: TCP
          volumeMounts:
            - name: blocky-config
              mountPath: /app/config.yml
              subPath: config.yml
      volumes:
        - name: blocky-config
          configMap:
            name: blocky-config
