apiVersion: apps/v1
kind: Deployment
metadata:
  name: unbound
  labels:
    app: unbound
    namespace: unbound
spec:
  selector:
    matchLabels:
      app: unbound
  replicas: 1
  template:
    metadata:
      labels:
        app: unbound
    spec:
      # initContainers:
      # - name: unbound-ads-conf
      #   image: alpine
      #   imagePullPolicy: IfNotPresent
      #   command: ["sh", "-c", "cd /unbound-ads && apk update && apk add ca-certificates && apk add wget && wget 'https://pgl.yoyo.org/adservers/serverlist.php?hostformat=unbound&showintro=0&mimetype=plaintext&useip=127.0.0.1' -O unbound-ad-servers" ]
      #   volumeMounts:
      #     - name: unbound-ads-conf-volume
      #       mountPath: /unbound-ads
      #
      containers:
        - name: unbound
          image: chandanghosh/unbound-docker:1.17
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 64Mi
              cpu: 10m
            limits:
              memory: 128Mi
              cpu: 100m
          ports:
            - name: svc-53-udp
              containerPort: 53
              protocol: UDP
            - name: svc-53-tcp
              containerPort: 53
              protocol: TCP
          volumeMounts:
            - name: unbound-main-conf-volume
              mountPath: /etc/unbound/unbound.conf
              subPath: unbound.conf
            - name: unbound-a-conf-volume
              mountPath: /etc/unbound/a-records.conf
              subPath: a-records.conf
            - name: unbound-forward-conf-volume
              mountPath: /etc/unbound/forward-records.conf
              subPath: forward-records.conf
            - name: unbound-srv-conf-volume
              mountPath: /opt/unbound/etc/unbound/srv-records.conf
              subPath: srv-records.conf
      restartPolicy: Always
      volumes:
        - name: unbound-main-conf-volume
          configMap:
            name: unbound-main-conf
        - name: unbound-a-conf-volume
          configMap:
            name: unbound-a-records-conf
        - name: unbound-forward-conf-volume
          configMap:
            name: unbound-forward-records-conf
        - name: unbound-srv-conf-volume
          configMap:
            name: unbound-srv-records-conf

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: unbound
  namespace: unbound
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: unbound
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 110Mi

---
apiVersion: v1
kind: Service
metadata:
  name: unbound-svc
  namespace: unbound
spec:
  selector:
    app: unbound
  ports:
    - name: tcp-svc
      protocol: TCP
      port: 53
      targetPort: 53
    - name: udp-svc
      protocol: UDP
      port: 53
      targetPort: 53
  externalTrafficPolicy: Local
  type: LoadBalancer
#   externalIPs:
#   - 10.27.27.119
#   - 10.27.27.120
---
apiVersion: v1
kind: Service
metadata:
  name: unbound-lb-svc
  namespace: unbound
spec:
  selector:
    app: unbound
  ports:
    - name: tcp-svc
      protocol: TCP
      port: 5335
      targetPort: 53
    - name: udp-svc
      protocol: UDP
      port: 5335
      targetPort: 53
  # externalTrafficPolicy: Local
  # type: LoadBalancer
  # externalIPs:
  # - 10.27.27.119
  # - 10.27.27.120

---

