apiVersion: v1
kind: Service
metadata:
  name: prometheus-backends
  namespace: monitoring
spec:
  ports:
    - name: web
      port: 9090
      targetPort: web
  selector:
    prometheus: prometheus-backends
  sessionAffinity: ClientIP
