apiVersion: 'acid.zalan.do/v1'
kind: postgresql
metadata:
  name: acid-minimal-cluster2
spec:
  teamId: 'acid2'

  numberOfInstances: 2
  users:
    zalando: # database owner
      - superuser
      - createdb
    foo_user: [] # role for application foo
  databases:
    foo: zalando # dbname: owner
  preparedDatabases:
    bar: {}
  postgresql:
    version: '15'
  volume:
    size: 500Mi
    storageClass: standard
