with-cloudflare:
	kubectl apply -f 01-namespaces.yaml,02-pihole-DoH-cloudflare.yaml,03-wireguard.yaml,04-pihole-ingress.yaml

with-upstream:
	kubectl apply -f 01-namespaces.yaml,02-pihole-upstream-dns.yaml,03-wireguard.yaml,04-pihole-ingress.yaml
