apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    prometheus: external-prometheus
    role: alert-rules
  name: prometheus-example-rules
  namespace: monitoring
spec:
  groups:
    - name: ./example.rules
      rules:
        # - alert: ExampleAlert
        #   expr: vector(1)
        #   labels:
        #     namespace: default

        - alert: BackupHours
          expr: hour() >= 0 <= 3
          #    expr: hour() >= 0 <= 24
          for: 1m
          labels:
            notification: none
          annotations:
            description: 'This alert fires during backup hours to inhibit others'

        # Alert for any instance that is unreachable for >2 minutes.
        - alert: service_down
          expr: up == 0
          for: 2m
          labels:
            severity: page
            name: service_down
          annotations:
            summary: 'Instance {{ $labels.instance }} down'
            description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 2 minutes.'

        - alert: backup_disk_usage
          expr: (pbs_used / pbs_size) > 0.7
          for: 2m
          labels:
            severity: page
            name: backup_disk_usage
          annotations:
            summary: 'Instance {{ $labels.instance }} nearly full'
            description: '{{ $labels.instance }} of job {{ $labels.job }} Proxmox Backup Storage nearly full'

        - alert: disk_usage
          expr: pve_disk_usage_bytes{job="pve-exporter"} / pve_disk_size_bytes{job="pve-exporter"} > 0.9
          for: 5m
          labels:
            severity: page
            name: disk_usage
          annotations:
            summary: 'Instance {{ $labels.instance }} disk space low'
            description: '{{ $labels.instance }} of job {{ $labels.job }} has low disk space free.'

        - alert: high_memory
          expr: pve_memory_usage_bytes{instance="172.30.100.31:9221",template!="1"} / pve_memory_size_bytes > 0.7
          for: 1m
          labels:
            severity: page
            name: high_memory
          annotations:
            summary: 'Instance {{ $labels.instance }} under high memory load'
            description: '{{ $labels.instance }} of job {{ $labels.job }} is under high memory load.'

        - alert: high_load
          expr: node_load1 > 1.0
          for: 60m
          labels:
            severity: page
            name: high_load
          annotations:
            summary: 'Instance {{ $labels.instance }} under high load'
            description: '{{ $labels.instance }} of job {{ $labels.job }} is under high load.'
        - alert: DiskWillFillIn4Hours
          #expr: predict_linear(node_filesystem_free{job="node_exporter at nextcloud"}[1h], 4 * 3600) < 0
          expr: predict_linear(node_filesystem_avail_bytes{mountpoint="/mnt/ncdata"}[1h], 4 * 3600) < 0
          for: 5m
          labels:
            severity: page
            name: DiskWillFillIn4Hours
        - alert: InstanceDown
          expr: up == 0
          for: 5m
          labels:
            severity: page
            name: InstanceDown
          annotations:
            summary: 'Instance {{ $labels.instance }} down'
            description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes.'
        # - alert: CubeDNS-Error
        #   expr: (coredns_panics_total) > 0
        #   for: 10s
        #   labels:
        #     severity: page
        #     name: CubeDNS-Error
        #     namespace: default
        #   annotations:
        #     summary: 'Instance {{ $labels.instance }} down'
        #     description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes.'
