apiVersion: v1
kind: Service
metadata:
  name: redis-replication-service-extern
  namespace: ot-operators
spec:
  selector:
    app: redis-replication
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  type: NodePort
---

